# Generated by Django 3.2.3 on 2021-05-30 23:55

from django.contrib.auth.hashers import make_password
from django.db import migrations


def add_users(apps, schema_editor):
    User = apps.get_model('core', 'User')

    User.objects.create(
        username='admin@example.com',
        email='admin@example.com',
        password=make_password('admin'),
        is_superuser=True,
        is_staff=True,
    )

    User.objects.create(
        username='signup@example.com',
        email='signup@example.com',
        password=make_password('soccer'),
        is_superuser=False,
        is_staff=False,
    )

    User.objects.create(
        username='owner@example.com',
        email='owner@example.com',
        password=make_password('soccer'),
        is_superuser=False,
        is_staff=False,
    )


def remove_default_user(apps, scheme_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(username='admin@example.com').delete()
    User.objects.filter(username='signup@example.com').delete()
    User.objects.filter(username='owner@example.com').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_country_choices'),
    ]

    operations = [
        migrations.RunPython(add_users, remove_default_user),
    ]
