# Generated by Django 3.2.3 on 2021-06-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_related_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='user',
            new_name='owner',
        ),
    ]
