# Generated by Django 3.2.3 on 2021-06-08 08:37

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_player_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(django.db.models.functions.text.Upper('first_name'), name='upper_first_name_index'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(django.db.models.functions.text.Upper('last_name'), name='upper_last_name_index'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['country'], name='country_index'),
        ),
    ]
