# Generated by Django 3.2.3 on 2021-06-08 09:11

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_index_on_players'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='team',
            index=models.Index(django.db.models.functions.text.Upper('name'), name='upper_name_index'),
        ),
    ]
