# Generated by Django 3.2.3 on 2021-06-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_team_upper_name_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['fee'], name='fee_index'),
        ),
    ]
